import type {
  AudioCue,
  Contraindication,
  ContentMeta,
  EquipmentId,
  Exercise,
  PhaseId,
  RedFlagId,
  StopCriterion,
} from '../domain/types'

/**
 * ENTWURF – Übungskatalog (Phase 3). Alle Inhalte sind NICHT fachlich geprüft (status 'draft').
 * Tage-Grenzen sind konservative Platzhalter und müssen von Hebamme/Physiotherapeutin
 * festgelegt werden (siehe docs/content-governance.md). Produktions-Builds dürfen nur
 * Inhalte mit status 'reviewed' ausspielen (siehe src/content/validate.ts).
 */

const draftMeta: ContentMeta = {
  evidenceLevel: 'practical_tip',
  sources: [],
  status: 'draft',
  draftedAt: '2026-10-05',
  reviewDue: '2027-10-05',
  note: 'Entwurf: Quelle, Evidenz und Freigabe im Fachreview ergänzen.',
}

const cesarean = (note = 'Bauch-/Narbenbelastung: nach Kaiserschnitt erst später und nur ohne Beschwerden.'): Contraindication => ({
  condition: 'cesarean_early',
  minDaysSinceBirth: 56,
  note,
})
const perineal = (): Contraindication => ({
  condition: 'perineal_early',
  minDaysSinceBirth: 28,
  note: 'Bei frischer Geburtsverletzung zunächst nur sanfte Varianten.',
})
const pressure = (): Contraindication => ({
  condition: 'pelvic_pressure',
  note: 'Bei Druck- oder Schweregefühl im Becken nicht anbieten.',
})
const pain = (): Contraindication => ({
  condition: 'pain',
  note: 'Bei mittleren oder starken Schmerzen nicht anbieten.',
})
const doming = (): Contraindication => ({
  condition: 'doming',
  note: 'Bei beobachteter Bauchwölbung (Doming) nicht anbieten, Regression wählen.',
})
const clearance = (): Contraindication => ({
  condition: 'no_clearance',
  note: 'Nur mit medizinischer Freigabe anbieten.',
})

const stop = (...extra: StopCriterion[]): StopCriterion[] => ['pain', 'pelvic_pressure', 'urine_leakage', ...extra]
const flags: RedFlagId[] = ['pain_increasing', 'pelvic_pressure_severe', 'symptom_worsening']

const cue = (trigger: AudioCue['trigger'], text: string): AudioCue => ({ trigger, text })

type Spec = Omit<Exercise, 'meta' | 'redFlags' | 'why' | 'focus' | 'requires' | 'oneHandFriendly' | 'bedFriendly' | 'domingWarning' | 'audioCues' | 'stopCriteria'> &
  Partial<Pick<Exercise, 'redFlags' | 'requires' | 'oneHandFriendly' | 'bedFriendly' | 'domingWarning' | 'audioCues' | 'stopCriteria'>>

function ex(s: Spec): Exercise {
  return {
    requires: [] as EquipmentId[],
    oneHandFriendly: false,
    bedFriendly: false,
    domingWarning: false,
    stopCriteria: stop(),
    // Standard-Cues: Start, Halbzeit, Ende; bei Wiederholungsübungen zusätzlich Atemrhythmus
    audioCues: [
      cue('start', `${s.name}. Beginne ruhig.`),
      cue('halfway', 'Halbzeit.'),
      ...(s.repetitions ? [cue('inhale', 'Einatmen.'), cue('exhale', 'Ausatmen und bewegen.')] : []),
      cue('end', 'Geschafft. Atme ruhig weiter.'),
    ],
    redFlags: flags,
    ...s,
    why: whyText[s.id] ?? '',
    focus: focusText[s.id] ?? '',
    meta: draftMeta,
  }
}

const p = (n: PhaseId): PhaseId => n

const focusText: Record<string, string> = {
  "belly-breathing": "Atme so, dass sich Bauch und Flanken sanft weiten. Die Schultern bleiben locker.",
  "pelvic-floor-awareness": "Du musst nichts anspannen. Nimm nur wahr, wie sich dein Beckenboden beim Atmen bewegt.",
  "pelvic-floor-release": "Lass wirklich los. Spürst du Druck oder Schmerz, höre auf.",
  "breath-pelvic-floor": "Heben nur ganz leicht und beim Ausatmen. Beim Einatmen vollständig loslassen, nicht pressen.",
  "pelvic-tilt": "Kleine, weiche Bewegung. Der Bauch soll sich nicht nach oben wölben.",
  "knee-sway": "Nur so weit, wie es angenehm ist. Zieht es an der Narbe oder im Bauch, mach die Bewegung kleiner.",
  "neck-shoulder-mobility": "Langsam bewegen und nie in den Schmerz hinein. Atme ruhig weiter.",
  "heel-slide": "Das Becken bleibt ruhig. Wölbt sich der Bauch in der Mitte, stoppe und wähle etwas Leichteres.",
  "glute-bridge": "Hebe das Becken beim Ausatmen und senke es langsam. Nicht ins Hohlkreuz drücken.",
  "clamshell": "Nur das Knie öffnet sich, das Becken bleibt ruhig und kippt nicht nach hinten.",
  "quadruped-weight-shift": "Schaukle langsam. Der Rücken bleibt gerade, der Bauch locker.",
  "cat-cow": "Bewege dich mit dem Atem, nicht ins Hohlkreuz drücken. Der Bauch bleibt weich.",
  "wall-pushup": "Beim Wegdrücken ausatmen, nicht pressen. Der Bauch bleibt locker.",
  "sit-to-stand": "Beim Aufstehen ausatmen und nicht pressen. Spürst du Druck im Becken, höre auf.",
  "marching-bridge": "Das Becken bleibt waagerecht. Hebe das Knie nur wenig an.",
  "dead-bug-heel-tap": "Der Rücken bleibt ruhig am Boden. Wölbt sich der Bauch nach oben, mach es leichter.",
  "bird-dog": "Becken und Rücken bleiben ruhig. Strecke nur so weit, wie du die Stabilität hältst.",
  "side-lying-leg-lift": "Das Bein nur kontrolliert anheben. Becken und Oberkörper bleiben still.",
  "supported-squat": "Halte dich fest und geh nur so tief, wie es angenehm ist. Beim Aufrichten ausatmen.",
  "dead-bug-alternating": "Der Rücken bleibt am Boden und der Bauch flach. Bei Wölbung oder Druck sofort leichter.",
  "single-leg-bridge": "Das Becken bleibt gerade. Wackelt es stark, nimm die einfachere Brücke.",
  "suitcase-carry": "Aufrecht gehen, nicht zur Seite kippen und weiteratmen. Nicht die Luft anhalten.",
  "foot-pumps": "Ganz ohne Kraft. Spürst du Schmerzen oder Schwellung im Bein, höre auf und lass es abklären.",
  "shoulder-blade-slide": "Nur die Schulterblätter bewegen, die Schultern nicht hochziehen.",
  "glute-squeeze": "Spanne nur leicht an, ohne zu pressen, und lass beim Einatmen ganz los.",
  "hand-wrist-release": "Bewege dich locker und ohne Kraft. Das darf angenehm sein.",
  "side-lying-breathing": "Spüre, wie sich die obere Rippenseite beim Einatmen weitet. Lass die Schultern schwer.",
  "lying-arm-stretch": "Führe die Arme nur so weit, wie es angenehm ist. Zieht es an der Narbe, bleib tiefer.",
  "ball-pelvic-circles": "Sitze aufrecht und halte dich notfalls an einer Wand fest. Kleine Kreise reichen.",
  "ball-squeeze-bridge": "Drücke den Ball sanft, nicht fest. Atme beim Anheben aus und presse nicht.",
  "band-row": "Ziehe die Ellenbogen nach hinten, nicht die Schultern nach oben. Atme beim Ziehen aus.",
  "band-clamshell": "Das Band soll nur leichten Widerstand geben. Das Becken bleibt ruhig.",
  "ball-wall-squat": "Geh nur so tief, wie es angenehm ist. Beim Aufrichten ausatmen, nicht pressen."
}

const whyText: Record<string, string> = {
  "belly-breathing": "Ruhiges Atmen in den Bauch und die Flanken beruhigt das Nervensystem und gibt dem Körper ein Signal zum Entspannen. Das Zwiebelfell der Atmung, das Zwerchfell, arbeitet außerdem eng mit dem Beckenboden und der tiefen Bauchmuskulatur zusammen. Deshalb beginnt fast alles mit der Atmung.",
  "pelvic-floor-awareness": "Bevor man den Beckenboden trainiert, hilft es, ihn erst einmal zu spüren. Viele Frauen merken nach der Geburt zunächst wenig von ihm. Wahrnehmen kommt vor Kraft: Wer weiß, wo er ist und wie er sich anfühlt, kann ihn später gezielter einsetzen.",
  "pelvic-floor-release": "Ein Beckenboden soll nicht nur anspannen, sondern auch loslassen können. Ein dauerhaft angespannter Beckenboden arbeitet nicht besser. Das bewusste Entspannen ist die Hälfte der Übung und wird oft vergessen.",
  "breath-pelvic-floor": "Beim Ausatmen hebt sich der Beckenboden von selbst ein wenig, beim Einatmen senkt er sich. Wer diese Bewegung bewusst mitmacht, verbindet Atmung und Beckenboden. Das ist die Grundlage für spätere Übungen, bei denen man beim Anstrengen ausatmet.",
  "pelvic-tilt": "Das kleine Kippen des Beckens mobilisiert den unteren Rücken und weckt die tiefe Bauchmuskulatur sanft. Es ist eine der einfachsten Übungen, um wieder ein Gefühl für die Mitte des Körpers zu bekommen.",
  "knee-sway": "Das sanfte Pendeln lockert Becken, Hüfte und unteren Rücken. Es fühlt sich oft nach langem Sitzen, Stillen oder Tragen wohltuend an und kostet fast keine Kraft.",
  "neck-shoulder-mobility": "Stillen, Tragen und Wickeln belasten Nacken und Schultern oft einseitig. Kurzes Lockern löst Verspannungen und lässt sich gut zwischendurch machen.",
  "heel-slide": "Das langsame Ausstrecken eines Beins bei ruhigem Becken übt, die tiefe Bauchmuskulatur zu aktivieren, ohne dass der Bauch nach oben wölbt. Es ist eine sanfte Vorstufe für anspruchsvollere Bauchübungen.",
  "glute-bridge": "Das Gesäß ist einer der größten Muskeln und stützt Becken und Rücken. Die Brücke kräftigt es und die Beinrückseite und lässt sich gut mit der Atmung kombinieren. Sie ist die Basis für viele Alltagsbewegungen wie Aufstehen und Treppensteigen.",
  "clamshell": "Die seitliche Hüftmuskulatur hält das Becken beim Gehen und Stehen stabil. Nach Schwangerschaft und Geburt ist sie oft schwächer. Die Muschel kräftigt sie in einer entspannten Seitenlage.",
  "quadruped-weight-shift": "Das sanfte Schaukeln im Vierfüßlerstand stabilisiert Schultern und Rumpf und bereitet auf Übungen wie den Bird Dog vor, ohne den Bauch stark zu fordern.",
  "cat-cow": "Das abwechselnde Runden und Öffnen des Rückens mobilisiert die Wirbelsäule und verbindet Bewegung mit der Atmung. Es löst Steifheit, besonders nach langem Sitzen oder Stillen.",
  "wall-pushup": "Die Wandvariante kräftigt Brust, Schultern und Arme, die beim Tragen und Heben des Babys viel leisten, und belastet dabei den Bauch kaum.",
  "sit-to-stand": "Aufstehen und Hinsetzen ist eine der häufigsten Alltagsbewegungen. Mit bewusster Atmung geübt, trainiert es Oberschenkel, Gesäß und Beckenboden alltagsnah.",
  "marching-bridge": "Das abwechselnde Anheben der Beine in der Brücke fordert das Becken, stabil zu bleiben. Das ist die Grundlage für sicheres Gehen und Laufen.",
  "dead-bug-heel-tap": "Die Beine abwechselnd absenken, während der Rücken ruhig bleibt, trainiert die tiefe Bauchmuskulatur im Zusammenspiel mit der Atmung. Es ist eine kontrollierte Steigerung gegenüber dem Fersen-Gleiten.",
  "bird-dog": "Arm und gegenüberliegendes Bein strecken fördert Koordination und Rumpfstabilität, ohne dass der Bauch stark nach vorn drückt.",
  "side-lying-leg-lift": "Das kontrollierte Anheben des Beins in Seitenlage kräftigt die seitliche Hüfte und das Gesäß weiter und führt die Muschel fort.",
  "supported-squat": "Mit Halt lassen sich Kniebeugen sicher üben. Sie kräftigen Beine und Gesäß und trainieren das Zusammenspiel von Atmung und Beckenboden beim Aufrichten.",
  "dead-bug-alternating": "Gegenüberliegender Arm und Bein im Wechsel fordern Bauch und Rumpf stärker. Sie sind eine spätere Stufe und nur sinnvoll, wenn der Bauch dabei ruhig bleibt.",
  "single-leg-bridge": "Die einbeinige Brücke ist eine Steigerung der Brücke und trainiert die Beckenstabilität auf einer Seite, wichtig fürs Gehen und Treppensteigen.",
  "suitcase-carry": "Ein Gewicht auf einer Seite zu tragen trainiert die Rumpfstabilität im Alltag, zum Beispiel beim Tragen von Einkäufen oder dem Baby auf einer Seite.",
  "foot-pumps": "Das Bewegen der Füße im Liegen hält die Gelenke beweglich und fühlt sich nach längerem Liegen oder Sitzen wohltuend an. Es braucht keinerlei Kraft.",
  "shoulder-blade-slide": "Das Zusammenführen der Schulterblätter richtet den oberen Rücken auf und wirkt der Rundhaltung vom Stillen und Tragen entgegen.",
  "glute-squeeze": "Das leichte Anspannen des Gesäßes ist eine sehr sanfte Kraftübung, die ohne Bewegung auskommt und sich im Bett oder auf dem Sofa machen lässt.",
  "hand-wrist-release": "Hände und Handgelenke werden beim Halten, Tragen und Stillen stark beansprucht. Lockern beugt Verspannungen vor.",
  "side-lying-breathing": "Atmen in Seitenlage weitet die Flanken und die Rippen und ist besonders bequem. Es eignet sich zum Ausruhen und für die Zeit, in der das Baby neben dir schläft.",
  "lying-arm-stretch": "Das Strecken der Arme über den Kopf öffnet Brustkorb und Rippen und löst Spannung in Schultern und Rücken, ganz ohne Aufwand im Liegen.",
  "ball-pelvic-circles": "Das Kreisen auf dem Gymnastikball mobilisiert Becken und unteren Rücken auf spielerische Weise und trainiert die Aufrichtung im Sitzen.",
  "ball-squeeze-bridge": "Der Ball zwischen den Knien aktiviert die Oberschenkelinnenseite, die mit dem Beckenboden zusammenspielt. In der Brücke wird so die Mitte des Beckens mitgefordert.",
  "band-row": "Rudern mit dem Band kräftigt den oberen Rücken, der beim Tragen und Stillen oft zu kurz kommt, und fördert eine aufrechte Haltung.",
  "band-clamshell": "Das Band erhöht den Widerstand in der Muschel und kräftigt die seitliche Hüfte weiter.",
  "ball-wall-squat": "Der Ball an der Wand führt die Kniebeuge sanft und hilft, die Bewegung sauber auszuführen. Er entlastet den Rücken."
}

export const exercises: Exercise[] = [
  // ---------- Phase 1: Recovery & Wahrnehmung ----------
  ex({
    id: 'belly-breathing',
    name: 'Bauchatmung',
    description: 'Ruhiges Atmen in Bauch und Flanken, um zu entspannen und den Körper wahrzunehmen.',
    instructions: ['Bequem liegen oder sitzen.', 'Eine Hand auf den Bauch legen.', 'Durch die Nase einatmen, Bauch und Rippen weiten sich.', 'Lang und locker ausatmen.'],
    breathing: 'Ein 4 s, aus 6 s',
    targetMuscles: ['Zwerchfell'],
    difficulty: 1,
    duration: 120,
    phase: p(1),
    regressions: [],
    progressions: ['breath-pelvic-floor'],
    contraindications: [],
    oneHandFriendly: true,
    audioCues: [cue('start', 'Mach es dir bequem.'), cue('inhale', 'Einatmen.'), cue('exhale', 'Langsam ausatmen.'), cue('end', 'Sehr gut.')],
    bedFriendly: true,
  }),
  ex({
    id: 'pelvic-floor-awareness',
    name: 'Beckenboden wahrnehmen',
    description: 'Den Beckenboden nur spüren, ohne ihn zu trainieren: Wo sitzt er, wie fühlt er sich an?',
    instructions: ['Bequem sitzen oder liegen.', 'Aufmerksamkeit zum Beckenboden lenken.', 'Beim Einatmen spüren, wie er sich leicht weitet.', 'Beim Ausatmen spüren, wie er sich leicht hebt.'],
    breathing: 'Natürlich weiteratmen',
    targetMuscles: ['Beckenboden'],
    difficulty: 1,
    duration: 120,
    phase: p(1),
    regressions: ['belly-breathing'],
    progressions: ['breath-pelvic-floor', 'pelvic-floor-release'],
    contraindications: [],
    oneHandFriendly: true,
    bedFriendly: true,
  }),
  ex({
    id: 'pelvic-floor-release',
    name: 'Beckenboden entspannen',
    description: 'Bewusstes Loslassen. Entspannung ist genauso wichtig wie Anspannung.',
    instructions: ['Bequem liegen, Knie angestellt.', 'Beim Einatmen den Beckenboden weit und weich lassen.', 'Beim Ausatmen nichts anspannen, einfach loslassen.'],
    breathing: 'Ein 4 s, aus 6 s',
    targetMuscles: ['Beckenboden'],
    difficulty: 1,
    duration: 120,
    phase: p(1),
    regressions: ['belly-breathing'],
    progressions: ['breath-pelvic-floor'],
    contraindications: [],
    oneHandFriendly: true,
    bedFriendly: true,
  }),
  ex({
    id: 'breath-pelvic-floor',
    name: 'Atmung und Beckenboden',
    description: 'Beim Ausatmen den Beckenboden sanft heben, beim Einatmen vollständig loslassen.',
    instructions: ['Bequem liegen oder sitzen.', 'Einatmen: Beckenboden loslassen.', 'Ausatmen: sanft und nur leicht anheben, nicht pressen.', 'Einatmen: wieder ganz loslassen.'],
    breathing: 'Ausatmen = sanftes Anheben',
    targetMuscles: ['Beckenboden', 'Zwerchfell'],
    difficulty: 1,
    duration: 150,
    repetitions: 8,
    phase: p(1),
    regressions: ['pelvic-floor-awareness'],
    progressions: ['pelvic-tilt'],
    contraindications: [pain()],
    stopCriteria: stop(),
    oneHandFriendly: true,
    audioCues: [cue('start', 'Einatmen und loslassen.'), cue('exhale', 'Ausatmen und sanft anheben.'), cue('inhale', 'Einatmen und ganz loslassen.'), cue('end', 'Gut gemacht.')],
    bedFriendly: true,
  }),
  ex({
    id: 'pelvic-tilt',
    name: 'Beckenkippen',
    description: 'Kleine Kippbewegung des Beckens in Rückenlage, um Becken und unteren Rücken zu mobilisieren.',
    instructions: ['Rückenlage, Knie angestellt.', 'Ausatmen: Becken leicht nach hinten kippen.', 'Einatmen: zurück in die Mitte.', 'Kleine, weiche Bewegung.'],
    breathing: 'Ausatmen beim Kippen',
    targetMuscles: ['Bauchmuskeln', 'Beckenboden'],
    difficulty: 1,
    duration: 90,
    repetitions: 8,
    phase: p(1),
    regressions: ['breath-pelvic-floor'],
    progressions: ['glute-bridge'],
    contraindications: [pain(), pressure(), cesarean('Nach Kaiserschnitt zunächst nur sehr kleine Bewegung, bei Narbenzug abbrechen.')],
    stopCriteria: stop('doming'),
    domingWarning: true,
    bedFriendly: true,
  }),
  ex({
    id: 'knee-sway',
    name: 'Knie-Pendeln',
    description: 'Sanftes seitliches Pendeln der Knie zur Mobilisation von Becken und Rücken.',
    instructions: ['Rückenlage, Füße aufgestellt.', 'Beide Knie langsam zu einer Seite sinken lassen.', 'Zurück zur Mitte und zur anderen Seite.'],
    breathing: 'Ruhig weiteratmen',
    targetMuscles: ['Rumpf', 'Hüfte'],
    difficulty: 1,
    duration: 90,
    repetitions: 8,
    phase: p(1),
    regressions: ['belly-breathing'],
    progressions: ['heel-slide'],
    contraindications: [pain(), cesarean('Nach Kaiserschnitt nur sehr kleine Bewegungen, bei Narbenzug abbrechen.')],
    bedFriendly: true,
  }),
  ex({
    id: 'neck-shoulder-mobility',
    name: 'Nacken & Schultern lockern',
    description: 'Sanfte Mobilisation für Nacken und Schultern, passend nach langem Stillen oder Tragen.',
    instructions: ['Aufrecht sitzen.', 'Schultern langsam kreisen.', 'Kopf behutsam zu einer Seite neigen und halten.', 'Seitenwechsel.'],
    breathing: 'Ruhig weiteratmen',
    targetMuscles: ['Nacken', 'Schultern'],
    difficulty: 1,
    duration: 120,
    phase: p(1),
    regressions: [],
    progressions: ['cat-cow'],
    contraindications: [],
    oneHandFriendly: true,
    bedFriendly: true,
  }),

  // ---------- Phase 2: Basis ----------
  ex({
    id: 'heel-slide',
    name: 'Fersen-Gleiten',
    description: 'Ein Bein langsam ausstrecken und zurückziehen, Becken bleibt ruhig.',
    instructions: ['Rückenlage, Knie angestellt.', 'Ausatmen: eine Ferse langsam wegschieben.', 'Einatmen: zurückziehen.', 'Seitenwechsel.'],
    breathing: 'Ausatmen beim Ausstrecken',
    targetMuscles: ['Tiefe Bauchmuskeln', 'Hüftbeuger'],
    difficulty: 1,
    duration: 120,
    repetitions: 8,
    phase: p(2),
    regressions: ['pelvic-tilt'],
    progressions: ['dead-bug-heel-tap'],
    contraindications: [pain(), pressure(), doming(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
    bedFriendly: true,
  }),
  ex({
    id: 'glute-bridge',
    name: 'Glute Bridge',
    description: 'Becken aus der Rückenlage anheben, aktiviert Gesäß und Rückseite der Beine.',
    instructions: ['Rückenlage, Füße hüftbreit aufstellen.', 'Ausatmen: Becken langsam anheben.', 'Oben kurz halten.', 'Einatmen: Wirbel für Wirbel absenken.'],
    breathing: 'Ausatmen beim Anheben',
    targetMuscles: ['Gesäß', 'Beinrückseite', 'Beckenboden'],
    difficulty: 2,
    duration: 150,
    repetitions: 10,
    phase: p(2),
    regressions: ['pelvic-tilt'],
    progressions: ['marching-bridge'],
    contraindications: [pain(), pressure(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
    audioCues: [cue('start', 'Füße hüftbreit.'), cue('exhale', 'Ausatmen und anheben.'), cue('inhale', 'Einatmen und langsam absenken.'), cue('halfway', 'Halbzeit.'), cue('end', 'Super.')],
  }),
  ex({
    id: 'clamshell',
    name: 'Clamshell',
    description: 'In Seitenlage das obere Knie öffnen, kräftigt die seitliche Hüftmuskulatur.',
    instructions: ['Seitenlage, Knie angewinkelt, Füße zusammen.', 'Ausatmen: oberes Knie öffnen, Becken bleibt ruhig.', 'Einatmen: schließen.', 'Seitenwechsel.'],
    breathing: 'Ausatmen beim Öffnen',
    targetMuscles: ['Seitliche Hüfte', 'Gesäß'],
    difficulty: 2,
    duration: 150,
    repetitions: 10,
    phase: p(2),
    regressions: ['pelvic-tilt'],
    progressions: ['side-lying-leg-lift'],
    contraindications: [pain(), pressure(), perineal()],
  }),
  ex({
    id: 'quadruped-weight-shift',
    name: 'Vierfüßler – Gewicht verlagern',
    description: 'Im Vierfüßlerstand sanft vor- und zurückschaukeln.',
    instructions: ['Vierfüßlerstand, Hände unter den Schultern.', 'Becken langsam Richtung Fersen schieben.', 'Zurück in die Ausgangsposition.'],
    breathing: 'Ausatmen beim Zurückschieben',
    targetMuscles: ['Rumpf', 'Schultern'],
    difficulty: 2,
    duration: 120,
    repetitions: 8,
    phase: p(2),
    regressions: ['pelvic-tilt'],
    progressions: ['bird-dog'],
    contraindications: [pain(), pressure(), doming(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'cat-cow',
    name: 'Katze-Kuh',
    description: 'Wirbelsäulen-Mobilisation im Vierfüßlerstand.',
    instructions: ['Vierfüßlerstand.', 'Ausatmen: Rücken sanft runden.', 'Einatmen: Brustbein leicht öffnen, nicht ins Hohlkreuz drücken.'],
    breathing: 'Ausatmen runden, einatmen öffnen',
    targetMuscles: ['Wirbelsäule', 'Rumpf'],
    difficulty: 1,
    duration: 120,
    repetitions: 8,
    phase: p(2),
    regressions: ['pelvic-tilt'],
    progressions: ['quadruped-weight-shift'],
    contraindications: [pain(), cesarean('Nach Kaiserschnitt Bewegung klein halten, bei Narbenzug abbrechen.')],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'wall-pushup',
    name: 'Wand-Liegestütz',
    description: 'Sanfte Kräftigung von Brust, Schultern und Armen im Stehen an der Wand.',
    instructions: ['Arm-Länge von der Wand stehen, Hände auf Schulterhöhe.', 'Einatmen: Ellenbogen beugen.', 'Ausatmen: wegdrücken.', 'Bauch dabei locker lassen, nicht pressen.'],
    breathing: 'Ausatmen beim Wegdrücken',
    targetMuscles: ['Brust', 'Schultern', 'Arme'],
    difficulty: 2,
    duration: 120,
    repetitions: 8,
    phase: p(2),
    regressions: ['neck-shoulder-mobility'],
    progressions: [],
    contraindications: [pain(), pressure(), doming(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'sit-to-stand',
    name: 'Aufstehen vom Stuhl',
    description: 'Alltagsnahe Kraftübung: Aufstehen und Hinsetzen mit bewusster Atmung.',
    instructions: ['Aufrecht an die Stuhlkante setzen.', 'Ausatmen: aufstehen.', 'Einatmen: langsam hinsetzen.', 'Nicht pressen.'],
    breathing: 'Ausatmen beim Aufstehen',
    targetMuscles: ['Oberschenkel', 'Gesäß', 'Beckenboden'],
    difficulty: 2,
    duration: 120,
    repetitions: 8,
    phase: p(2),
    regressions: ['glute-bridge'],
    progressions: ['supported-squat'],
    contraindications: [pain(), pressure(), cesarean()],
    requires: ['chair'],
  }),

  // ---------- Phase 3: Aufbau ----------
  ex({
    id: 'marching-bridge',
    name: 'Marching Bridge',
    description: 'Aus der Brücke abwechselnd ein Bein anheben.',
    instructions: ['Glute Bridge einnehmen und halten.', 'Ausatmen: ein Knie leicht anheben.', 'Einatmen: abstellen.', 'Becken bleibt stabil, Seitenwechsel.'],
    breathing: 'Ausatmen beim Anheben',
    targetMuscles: ['Gesäß', 'Rumpf'],
    difficulty: 3,
    duration: 150,
    repetitions: 10,
    phase: p(3),
    regressions: ['glute-bridge'],
    progressions: [],
    contraindications: [pain(), pressure(), doming(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'dead-bug-heel-tap',
    name: 'Sanfter Dead Bug – Fersen-Tippen',
    description: 'Beine abwechselnd im 90°-Winkel absenken und antippen, Rücken bleibt ruhig.',
    instructions: ['Rückenlage, Knie über der Hüfte im 90°-Winkel.', 'Ausatmen: eine Ferse Richtung Boden tippen.', 'Einatmen: zurück.', 'Seitenwechsel.'],
    breathing: 'Ausatmen beim Absenken',
    targetMuscles: ['Tiefe Bauchmuskeln'],
    difficulty: 3,
    duration: 150,
    repetitions: 8,
    phase: p(3),
    regressions: ['heel-slide'],
    progressions: ['dead-bug-alternating'],
    contraindications: [pain(), pressure(), doming(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'bird-dog',
    name: 'Bird Dog',
    description: 'Im Vierfüßlerstand Arm und gegenüberliegendes Bein strecken.',
    instructions: ['Vierfüßlerstand.', 'Ausatmen: ein Bein nach hinten schieben.', 'Später gegenüberliegenden Arm dazunehmen.', 'Becken bleibt ruhig.'],
    breathing: 'Ausatmen beim Strecken',
    targetMuscles: ['Rumpf', 'Gesäß', 'Rücken'],
    difficulty: 3,
    duration: 150,
    repetitions: 8,
    phase: p(3),
    regressions: ['quadruped-weight-shift'],
    progressions: [],
    contraindications: [pain(), pressure(), doming(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'side-lying-leg-lift',
    name: 'Seitliches Beinheben',
    description: 'In Seitenlage das obere Bein kontrolliert anheben.',
    instructions: ['Seitenlage, unteres Bein angewinkelt.', 'Ausatmen: oberes Bein gestreckt anheben.', 'Einatmen: kontrolliert absenken.'],
    breathing: 'Ausatmen beim Anheben',
    targetMuscles: ['Seitliche Hüfte', 'Gesäß'],
    difficulty: 3,
    duration: 150,
    repetitions: 10,
    phase: p(3),
    regressions: ['clamshell'],
    progressions: [],
    contraindications: [pain(), pressure(), perineal()],
  }),
  ex({
    id: 'supported-squat',
    name: 'Kniebeuge mit Halt',
    description: 'Kniebeuge mit Festhalten an Stuhl oder Türrahmen.',
    instructions: ['Hüftbreit stehen, Halt greifen.', 'Einatmen: Gesäß nach hinten unten schieben.', 'Ausatmen: aufrichten.', 'Nicht pressen.'],
    breathing: 'Ausatmen beim Aufrichten',
    targetMuscles: ['Oberschenkel', 'Gesäß', 'Beckenboden'],
    difficulty: 3,
    duration: 150,
    repetitions: 10,
    phase: p(3),
    regressions: ['sit-to-stand'],
    progressions: [],
    contraindications: [pain(), pressure(), cesarean()],

  }),

  // ---------- Phase 4: Belastbarkeit ----------
  ex({
    id: 'dead-bug-alternating',
    name: 'Dead Bug – Arm & Bein',
    description: 'Gegenüberliegende Arm-Bein-Bewegung in Rückenlage.',
    instructions: ['Rückenlage, Arme zur Decke, Knie im 90°-Winkel.', 'Ausatmen: gegenüberliegenden Arm und Bein absenken.', 'Einatmen: zurück.', 'Rücken bleibt ruhig.'],
    breathing: 'Ausatmen beim Absenken',
    targetMuscles: ['Tiefe Bauchmuskeln', 'Rumpf'],
    difficulty: 4,
    duration: 180,
    repetitions: 8,
    phase: p(4),
    regressions: ['dead-bug-heel-tap'],
    progressions: [],
    contraindications: [pain(), pressure(), doming(), cesarean(), clearance()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'single-leg-bridge',
    name: 'Einbeinige Brücke',
    description: 'Glute Bridge mit einem ausgestreckten Bein.',
    instructions: ['Glute Bridge einnehmen.', 'Ein Bein strecken.', 'Becken waagerecht halten, Ausatmen beim Anheben.'],
    breathing: 'Ausatmen beim Anheben',
    targetMuscles: ['Gesäß', 'Beinrückseite', 'Rumpf'],
    difficulty: 4,
    duration: 180,
    repetitions: 8,
    phase: p(4),
    regressions: ['marching-bridge'],
    progressions: [],
    contraindications: [pain(), pressure(), doming(), cesarean(), clearance()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'suitcase-carry',
    name: 'Koffer-Tragen',
    description: 'Leichtes Gewicht aufrecht tragen, trainiert Rumpfstabilität im Alltag.',
    instructions: ['Gewicht mit einer Hand tragen.', 'Aufrecht gehen, Schultern locker.', 'Gleichmäßig atmen, nicht Luft anhalten.', 'Seitenwechsel.'],
    breathing: 'Gleichmäßig atmen',
    targetMuscles: ['Rumpf', 'Schultern', 'Hüfte'],
    difficulty: 4,
    duration: 120,
    phase: p(4),
    regressions: ['supported-squat'],
    progressions: [],
    contraindications: [pain(), pressure(), doming(), cesarean(), clearance()],
    stopCriteria: stop('doming'),
    domingWarning: true,
    requires: ['weight'],
  }),

  // ---------- Kleine Übungen für nebenbei im Bett / auf dem Sofa (Phase 1) ----------
  ex({
    id: 'foot-pumps',
    name: 'Fußpumpen und Fußkreisen',
    description: 'Im Liegen die Füße bewegen: hoch, runter und kreisen. Ganz ohne Kraft.',
    instructions: ['Bequem liegen oder sitzen, Beine locker.', 'Füße abwechselnd Richtung Gesicht ziehen und wieder strecken.', 'Danach beide Füße langsam kreisen lassen, in beide Richtungen.'],
    breathing: 'Ruhig weiteratmen',
    targetMuscles: ['Füße', 'Waden'],
    difficulty: 1,
    duration: 60,
    phase: p(1),
    regressions: [],
    progressions: ['knee-sway'],
    contraindications: [{ condition: 'pain', note: 'Bei Schmerzen im Bein nicht üben.' }],
    redFlags: ['leg_swelling', 'pain_increasing', 'symptom_worsening'],
    oneHandFriendly: true,
    bedFriendly: true,
  }),
  ex({
    id: 'shoulder-blade-slide',
    name: 'Schulterblätter zusammenführen',
    description: 'Im Liegen oder Sitzen die Schulterblätter sanft zur Wirbelsäule ziehen.',
    instructions: ['Aufrecht sitzen oder auf dem Rücken liegen.', 'Beim Ausatmen die Schulterblätter sanft zusammen- und nach unten ziehen.', 'Kurz halten, beim Einatmen lösen.'],
    breathing: 'Ausatmen beim Zusammenführen',
    targetMuscles: ['Oberer Rücken'],
    difficulty: 1,
    duration: 90,
    repetitions: 8,
    phase: p(1),
    regressions: [],
    progressions: ['cat-cow'],
    contraindications: [pain()],
    bedFriendly: true,
  }),
  ex({
    id: 'glute-squeeze',
    name: 'Gesäß leicht anspannen',
    description: 'Das Gesäß im Liegen bewusst leicht anspannen und wieder lösen.',
    instructions: ['Auf dem Rücken oder in Seitenlage liegen.', 'Beim Ausatmen das Gesäß sanft anspannen, nicht stark pressen.', 'Beim Einatmen vollständig loslassen.'],
    breathing: 'Ausatmen beim Anspannen',
    targetMuscles: ['Gesäß'],
    difficulty: 1,
    duration: 90,
    repetitions: 8,
    phase: p(1),
    regressions: [],
    progressions: ['glute-bridge'],
    contraindications: [pain(), pressure(), perineal()],
    bedFriendly: true,
    oneHandFriendly: true,
  }),
  ex({
    id: 'hand-wrist-release',
    name: 'Hände und Handgelenke lockern',
    description: 'Finger spreizen, Handgelenke kreisen und ausschütteln, zum Beispiel beim Stillen.',
    instructions: ['Hände auf den Oberschenkeln oder in der Luft halten.', 'Finger öffnen und schließen.', 'Handgelenke langsam kreisen lassen.', 'Zum Schluss locker ausschütteln.'],
    breathing: 'Ruhig weiteratmen',
    targetMuscles: ['Hände', 'Unterarme'],
    difficulty: 1,
    duration: 60,
    phase: p(1),
    regressions: [],
    progressions: [],
    contraindications: [],
    bedFriendly: true,
    oneHandFriendly: true,
  }),
  ex({
    id: 'side-lying-breathing',
    name: 'Atmen in Seitenlage',
    description: 'In Seitenlage tief in die Flanken und die obere Rippenseite atmen.',
    instructions: ['Bequem auf die Seite legen, ein Kissen zwischen die Knie.', 'Eine Hand auf die obere Rippenseite legen.', 'Beim Einatmen spüren, wie sich die Rippen unter der Hand weiten.', 'Lang ausatmen.'],
    breathing: 'Ein 4 s, aus 6 s',
    targetMuscles: ['Zwerchfell', 'Rippen'],
    difficulty: 1,
    duration: 120,
    phase: p(1),
    regressions: [],
    progressions: ['breath-pelvic-floor'],
    contraindications: [],
    bedFriendly: true,
    oneHandFriendly: true,
    audioCues: [cue('start', 'Lege dich bequem auf die Seite.'), cue('inhale', 'Einatmen in die Flanke.'), cue('exhale', 'Langsam ausatmen.'), cue('end', 'Schön ruhig.')],
  }),
  ex({
    id: 'lying-arm-stretch',
    name: 'Arme über den Kopf strecken',
    description: 'Im Liegen die Arme langsam über den Kopf führen und den Brustkorb öffnen.',
    instructions: ['Auf dem Rücken liegen, Knie angestellt.', 'Beim Einatmen die Arme langsam über den Kopf führen, so weit es angenehm ist.', 'Beim Ausatmen zurückführen.'],
    breathing: 'Ein beim Heben, aus beim Senken',
    targetMuscles: ['Schultern', 'Brustkorb'],
    difficulty: 1,
    duration: 90,
    repetitions: 6,
    phase: p(1),
    regressions: [],
    progressions: ['cat-cow'],
    contraindications: [pain(), cesarean('Nach Kaiserschnitt Arme nur so weit führen, dass die Narbe nicht zieht.')],
    bedFriendly: true,
  }),

  // ---------- Mit Trainingsmitteln ----------
  ex({
    id: 'ball-pelvic-circles',
    name: 'Becken-Kreisen auf dem Gymnastikball',
    description: 'Aufrecht auf dem Ball sitzen und das Becken in kleinen Kreisen bewegen.',
    instructions: ['Auf den Ball setzen, Füße hüftbreit auf dem Boden, Wand oder Tisch in Reichweite.', 'Becken langsam in kleinen Kreisen bewegen.', 'Nach der Hälfte die Richtung wechseln.'],
    breathing: 'Ruhig weiteratmen',
    targetMuscles: ['Becken', 'Unterer Rücken'],
    difficulty: 1,
    duration: 120,
    phase: p(2),
    regressions: [],
    progressions: ['ball-squeeze-bridge'],
    contraindications: [pain(), pressure(), perineal()],
    requires: ['gymball'],
  }),
  ex({
    id: 'ball-squeeze-bridge',
    name: 'Brücke mit Ball zwischen den Knien',
    description: 'Glute Bridge mit einem Ball, der sanft zwischen den Knien gehalten wird.',
    instructions: ['Rückenlage, Ball zwischen den Knien.', 'Beim Ausatmen den Ball sanft drücken und das Becken anheben.', 'Beim Einatmen langsam absenken.'],
    breathing: 'Ausatmen beim Anheben',
    targetMuscles: ['Gesäß', 'Oberschenkelinnenseite', 'Beckenboden'],
    difficulty: 2,
    duration: 150,
    repetitions: 8,
    phase: p(2),
    regressions: ['pelvic-tilt'],
    progressions: [],
    contraindications: [pain(), pressure(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
    requires: ['gymball'],
  }),
  ex({
    id: 'band-row',
    name: 'Rudern mit dem Band',
    description: 'Im Sitzen ein Band zum Körper ziehen, kräftigt den oberen Rücken.',
    instructions: ['Aufrecht sitzen, Band um die Füße legen oder an einer Tür befestigen.', 'Beim Ausatmen die Ellenbogen nach hinten führen.', 'Beim Einatmen kontrolliert zurückgehen.'],
    breathing: 'Ausatmen beim Ziehen',
    targetMuscles: ['Oberer Rücken', 'Schultern'],
    difficulty: 2,
    duration: 120,
    repetitions: 10,
    phase: p(2),
    regressions: ['neck-shoulder-mobility'],
    progressions: [],
    contraindications: [pain(), pressure(), cesarean()],
    requires: ['band'],
  }),
  ex({
    id: 'band-clamshell',
    name: 'Muschel mit Band',
    description: 'Clamshell mit einem Band um die Oberschenkel für mehr Widerstand.',
    instructions: ['Seitenlage, Band knapp über den Knien.', 'Beim Ausatmen das obere Knie öffnen, Becken bleibt ruhig.', 'Beim Einatmen schließen.'],
    breathing: 'Ausatmen beim Öffnen',
    targetMuscles: ['Seitliche Hüfte', 'Gesäß'],
    difficulty: 3,
    duration: 150,
    repetitions: 10,
    phase: p(3),
    regressions: ['clamshell'],
    progressions: [],
    contraindications: [pain(), pressure(), perineal()],
    requires: ['band'],
  }),
  ex({
    id: 'ball-wall-squat',
    name: 'Wand-Kniebeuge mit Ball',
    description: 'Kniebeuge mit dem Ball zwischen Rücken und Wand.',
    instructions: ['Ball zwischen unteren Rücken und Wand klemmen, Füße etwas vor dem Körper.', 'Beim Einatmen langsam in die Knie gehen.', 'Beim Ausatmen aufrichten.'],
    breathing: 'Ausatmen beim Aufrichten',
    targetMuscles: ['Oberschenkel', 'Gesäß', 'Beckenboden'],
    difficulty: 3,
    duration: 150,
    repetitions: 8,
    phase: p(3),
    regressions: ['sit-to-stand'],
    progressions: [],
    contraindications: [pain(), pressure(), cesarean()],
    requires: ['gymball'],
  }),
]

export const exerciseById = (id: string): Exercise | undefined => exercises.find((e) => e.id === id)
