import type {
  AudioCue,
  Contraindication,
  ContentMeta,
  Exercise,
  PhaseId,
  RedFlagId,
  StopCriterion,
} from '../domain/types'

/**
 * ENTWURF – Übungskatalog (Phase 3). Alle Inhalte sind NICHT fachlich geprüft (status 'draft').
 * Tage-Grenzen sind konservative Platzhalter und müssen von Hebamme/Physiotherapeutin
 * festgelegt werden (siehe docs/content-governance.md). Produktions-Builds dürfen nur
 * Inhalte mit status 'reviewed' ausspielen (siehe src/content/validate.ts).
 */

const draftMeta: ContentMeta = {
  evidenceLevel: 'practical_tip',
  sources: [],
  status: 'draft',
  draftedAt: '2026-10-05',
  reviewDue: '2027-10-05',
  note: 'Entwurf: Quelle, Evidenz und Freigabe im Fachreview ergänzen.',
}

const cesarean = (note = 'Bauch-/Narbenbelastung: nach Kaiserschnitt erst später und nur ohne Beschwerden.'): Contraindication => ({
  condition: 'cesarean_early',
  minDaysSinceBirth: 56,
  note,
})
const perineal = (): Contraindication => ({
  condition: 'perineal_early',
  minDaysSinceBirth: 28,
  note: 'Bei frischer Geburtsverletzung zunächst nur sanfte Varianten.',
})
const pressure = (): Contraindication => ({
  condition: 'pelvic_pressure',
  note: 'Bei Druck- oder Schweregefühl im Becken nicht anbieten.',
})
const pain = (): Contraindication => ({
  condition: 'pain',
  note: 'Bei mittleren oder starken Schmerzen nicht anbieten.',
})
const doming = (): Contraindication => ({
  condition: 'doming',
  note: 'Bei beobachteter Bauchwölbung (Doming) nicht anbieten, Regression wählen.',
})
const clearance = (): Contraindication => ({
  condition: 'no_clearance',
  note: 'Nur mit medizinischer Freigabe anbieten.',
})

const stop = (...extra: StopCriterion[]): StopCriterion[] => ['pain', 'pelvic_pressure', 'urine_leakage', ...extra]
const flags: RedFlagId[] = ['pain_increasing', 'pelvic_pressure_severe', 'symptom_worsening']

const cue = (trigger: AudioCue['trigger'], text: string): AudioCue => ({ trigger, text })

type Spec = Omit<Exercise, 'meta' | 'redFlags' | 'equipment' | 'oneHandFriendly' | 'domingWarning' | 'audioCues' | 'stopCriteria'> &
  Partial<Pick<Exercise, 'equipment' | 'oneHandFriendly' | 'domingWarning' | 'audioCues' | 'stopCriteria'>>

function ex(s: Spec): Exercise {
  return {
    equipment: [],
    oneHandFriendly: false,
    domingWarning: false,
    stopCriteria: stop(),
    audioCues: [cue('start', `${s.name}. Beginne ruhig.`), cue('end', 'Geschafft. Atme ruhig weiter.')],
    ...s,
    redFlags: flags,
    meta: draftMeta,
  }
}

const p = (n: PhaseId): PhaseId => n

export const exercises: Exercise[] = [
  // ---------- Phase 1: Recovery & Wahrnehmung ----------
  ex({
    id: 'belly-breathing',
    name: 'Bauchatmung',
    description: 'Ruhiges Atmen in Bauch und Flanken, um zu entspannen und den Körper wahrzunehmen.',
    instructions: ['Bequem liegen oder sitzen.', 'Eine Hand auf den Bauch legen.', 'Durch die Nase einatmen, Bauch und Rippen weiten sich.', 'Lang und locker ausatmen.'],
    breathing: 'Ein 4 s, aus 6 s',
    targetMuscles: ['Zwerchfell'],
    difficulty: 1,
    duration: 120,
    phase: p(1),
    regressions: [],
    progressions: ['breath-pelvic-floor'],
    contraindications: [],
    oneHandFriendly: true,
    audioCues: [cue('start', 'Mach es dir bequem.'), cue('inhale', 'Einatmen.'), cue('exhale', 'Langsam ausatmen.'), cue('end', 'Sehr gut.')],
  }),
  ex({
    id: 'pelvic-floor-awareness',
    name: 'Beckenboden wahrnehmen',
    description: 'Den Beckenboden nur spüren, ohne ihn zu trainieren: Wo sitzt er, wie fühlt er sich an?',
    instructions: ['Bequem sitzen oder liegen.', 'Aufmerksamkeit zum Beckenboden lenken.', 'Beim Einatmen spüren, wie er sich leicht weitet.', 'Beim Ausatmen spüren, wie er sich leicht hebt.'],
    breathing: 'Natürlich weiteratmen',
    targetMuscles: ['Beckenboden'],
    difficulty: 1,
    duration: 120,
    phase: p(1),
    regressions: ['belly-breathing'],
    progressions: ['breath-pelvic-floor', 'pelvic-floor-release'],
    contraindications: [],
    oneHandFriendly: true,
  }),
  ex({
    id: 'pelvic-floor-release',
    name: 'Beckenboden entspannen',
    description: 'Bewusstes Loslassen. Entspannung ist genauso wichtig wie Anspannung.',
    instructions: ['Bequem liegen, Knie angestellt.', 'Beim Einatmen den Beckenboden weit und weich lassen.', 'Beim Ausatmen nichts anspannen, einfach loslassen.'],
    breathing: 'Ein 4 s, aus 6 s',
    targetMuscles: ['Beckenboden'],
    difficulty: 1,
    duration: 120,
    phase: p(1),
    regressions: ['belly-breathing'],
    progressions: ['breath-pelvic-floor'],
    contraindications: [],
    oneHandFriendly: true,
  }),
  ex({
    id: 'breath-pelvic-floor',
    name: 'Atmung und Beckenboden',
    description: 'Beim Ausatmen den Beckenboden sanft heben, beim Einatmen vollständig loslassen.',
    instructions: ['Bequem liegen oder sitzen.', 'Einatmen: Beckenboden loslassen.', 'Ausatmen: sanft und nur leicht anheben, nicht pressen.', 'Einatmen: wieder ganz loslassen.'],
    breathing: 'Ausatmen = sanftes Anheben',
    targetMuscles: ['Beckenboden', 'Zwerchfell'],
    difficulty: 1,
    duration: 150,
    repetitions: 8,
    phase: p(1),
    regressions: ['pelvic-floor-awareness'],
    progressions: ['pelvic-tilt'],
    contraindications: [pain()],
    stopCriteria: stop(),
    oneHandFriendly: true,
    audioCues: [cue('start', 'Einatmen und loslassen.'), cue('exhale', 'Ausatmen und sanft anheben.'), cue('inhale', 'Einatmen und ganz loslassen.'), cue('end', 'Gut gemacht.')],
  }),
  ex({
    id: 'pelvic-tilt',
    name: 'Beckenkippen',
    description: 'Kleine Kippbewegung des Beckens in Rückenlage, um Becken und unteren Rücken zu mobilisieren.',
    instructions: ['Rückenlage, Knie angestellt.', 'Ausatmen: Becken leicht nach hinten kippen.', 'Einatmen: zurück in die Mitte.', 'Kleine, weiche Bewegung.'],
    breathing: 'Ausatmen beim Kippen',
    targetMuscles: ['Bauchmuskeln', 'Beckenboden'],
    difficulty: 1,
    duration: 90,
    repetitions: 8,
    phase: p(1),
    regressions: ['breath-pelvic-floor'],
    progressions: ['glute-bridge'],
    contraindications: [pain(), pressure(), cesarean('Nach Kaiserschnitt zunächst nur sehr kleine Bewegung, bei Narbenzug abbrechen.')],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'knee-sway',
    name: 'Knie-Pendeln',
    description: 'Sanftes seitliches Pendeln der Knie zur Mobilisation von Becken und Rücken.',
    instructions: ['Rückenlage, Füße aufgestellt.', 'Beide Knie langsam zu einer Seite sinken lassen.', 'Zurück zur Mitte und zur anderen Seite.'],
    breathing: 'Ruhig weiteratmen',
    targetMuscles: ['Rumpf', 'Hüfte'],
    difficulty: 1,
    duration: 90,
    repetitions: 8,
    phase: p(1),
    regressions: ['belly-breathing'],
    progressions: ['heel-slide'],
    contraindications: [pain(), cesarean('Nach Kaiserschnitt nur sehr kleine Bewegungen, bei Narbenzug abbrechen.')],
  }),
  ex({
    id: 'neck-shoulder-mobility',
    name: 'Nacken & Schultern lockern',
    description: 'Sanfte Mobilisation für Nacken und Schultern, passend nach langem Stillen oder Tragen.',
    instructions: ['Aufrecht sitzen.', 'Schultern langsam kreisen.', 'Kopf behutsam zu einer Seite neigen und halten.', 'Seitenwechsel.'],
    breathing: 'Ruhig weiteratmen',
    targetMuscles: ['Nacken', 'Schultern'],
    difficulty: 1,
    duration: 120,
    phase: p(1),
    regressions: [],
    progressions: ['cat-cow'],
    contraindications: [],
    oneHandFriendly: true,
  }),

  // ---------- Phase 2: Basis ----------
  ex({
    id: 'heel-slide',
    name: 'Fersen-Gleiten',
    description: 'Ein Bein langsam ausstrecken und zurückziehen, Becken bleibt ruhig.',
    instructions: ['Rückenlage, Knie angestellt.', 'Ausatmen: eine Ferse langsam wegschieben.', 'Einatmen: zurückziehen.', 'Seitenwechsel.'],
    breathing: 'Ausatmen beim Ausstrecken',
    targetMuscles: ['Tiefe Bauchmuskeln', 'Hüftbeuger'],
    difficulty: 1,
    duration: 120,
    repetitions: 8,
    phase: p(2),
    regressions: ['pelvic-tilt'],
    progressions: ['dead-bug-heel-tap'],
    contraindications: [pain(), pressure(), doming(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'glute-bridge',
    name: 'Glute Bridge',
    description: 'Becken aus der Rückenlage anheben, aktiviert Gesäß und Rückseite der Beine.',
    instructions: ['Rückenlage, Füße hüftbreit aufstellen.', 'Ausatmen: Becken langsam anheben.', 'Oben kurz halten.', 'Einatmen: Wirbel für Wirbel absenken.'],
    breathing: 'Ausatmen beim Anheben',
    targetMuscles: ['Gesäß', 'Beinrückseite', 'Beckenboden'],
    difficulty: 2,
    duration: 150,
    repetitions: 10,
    phase: p(2),
    regressions: ['pelvic-tilt'],
    progressions: ['marching-bridge'],
    contraindications: [pain(), pressure(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
    audioCues: [cue('start', 'Füße hüftbreit.'), cue('exhale', 'Ausatmen und anheben.'), cue('inhale', 'Einatmen und langsam absenken.'), cue('halfway', 'Halbzeit.'), cue('end', 'Super.')],
  }),
  ex({
    id: 'clamshell',
    name: 'Clamshell',
    description: 'In Seitenlage das obere Knie öffnen, kräftigt die seitliche Hüftmuskulatur.',
    instructions: ['Seitenlage, Knie angewinkelt, Füße zusammen.', 'Ausatmen: oberes Knie öffnen, Becken bleibt ruhig.', 'Einatmen: schließen.', 'Seitenwechsel.'],
    breathing: 'Ausatmen beim Öffnen',
    targetMuscles: ['Seitliche Hüfte', 'Gesäß'],
    difficulty: 2,
    duration: 150,
    repetitions: 10,
    phase: p(2),
    regressions: ['pelvic-tilt'],
    progressions: ['side-lying-leg-lift'],
    contraindications: [pain(), pressure(), perineal()],
  }),
  ex({
    id: 'quadruped-weight-shift',
    name: 'Vierfüßler – Gewicht verlagern',
    description: 'Im Vierfüßlerstand sanft vor- und zurückschaukeln.',
    instructions: ['Vierfüßlerstand, Hände unter den Schultern.', 'Becken langsam Richtung Fersen schieben.', 'Zurück in die Ausgangsposition.'],
    breathing: 'Ausatmen beim Zurückschieben',
    targetMuscles: ['Rumpf', 'Schultern'],
    difficulty: 2,
    duration: 120,
    repetitions: 8,
    phase: p(2),
    regressions: ['pelvic-tilt'],
    progressions: ['bird-dog'],
    contraindications: [pain(), pressure(), doming(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'cat-cow',
    name: 'Katze-Kuh',
    description: 'Wirbelsäulen-Mobilisation im Vierfüßlerstand.',
    instructions: ['Vierfüßlerstand.', 'Ausatmen: Rücken sanft runden.', 'Einatmen: Brustbein leicht öffnen, nicht ins Hohlkreuz drücken.'],
    breathing: 'Ausatmen runden, einatmen öffnen',
    targetMuscles: ['Wirbelsäule', 'Rumpf'],
    difficulty: 1,
    duration: 120,
    repetitions: 8,
    phase: p(2),
    regressions: ['pelvic-tilt'],
    progressions: ['quadruped-weight-shift'],
    contraindications: [pain(), cesarean('Nach Kaiserschnitt Bewegung klein halten, bei Narbenzug abbrechen.')],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'wall-pushup',
    name: 'Wand-Liegestütz',
    description: 'Sanfte Kräftigung von Brust, Schultern und Armen im Stehen an der Wand.',
    instructions: ['Arm-Länge von der Wand stehen, Hände auf Schulterhöhe.', 'Einatmen: Ellenbogen beugen.', 'Ausatmen: wegdrücken.', 'Bauch dabei locker lassen, nicht pressen.'],
    breathing: 'Ausatmen beim Wegdrücken',
    targetMuscles: ['Brust', 'Schultern', 'Arme'],
    difficulty: 2,
    duration: 120,
    repetitions: 8,
    phase: p(2),
    regressions: ['neck-shoulder-mobility'],
    progressions: [],
    contraindications: [pain(), pressure(), doming(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'sit-to-stand',
    name: 'Aufstehen vom Stuhl',
    description: 'Alltagsnahe Kraftübung: Aufstehen und Hinsetzen mit bewusster Atmung.',
    instructions: ['Aufrecht an die Stuhlkante setzen.', 'Ausatmen: aufstehen.', 'Einatmen: langsam hinsetzen.', 'Nicht pressen.'],
    breathing: 'Ausatmen beim Aufstehen',
    targetMuscles: ['Oberschenkel', 'Gesäß', 'Beckenboden'],
    difficulty: 2,
    duration: 120,
    repetitions: 8,
    phase: p(2),
    regressions: ['glute-bridge'],
    progressions: ['supported-squat'],
    contraindications: [pain(), pressure(), cesarean()],
    equipment: ['Stuhl'],
  }),

  // ---------- Phase 3: Aufbau ----------
  ex({
    id: 'marching-bridge',
    name: 'Marching Bridge',
    description: 'Aus der Brücke abwechselnd ein Bein anheben.',
    instructions: ['Glute Bridge einnehmen und halten.', 'Ausatmen: ein Knie leicht anheben.', 'Einatmen: abstellen.', 'Becken bleibt stabil, Seitenwechsel.'],
    breathing: 'Ausatmen beim Anheben',
    targetMuscles: ['Gesäß', 'Rumpf'],
    difficulty: 3,
    duration: 150,
    repetitions: 10,
    phase: p(3),
    regressions: ['glute-bridge'],
    progressions: [],
    contraindications: [pain(), pressure(), doming(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'dead-bug-heel-tap',
    name: 'Sanfter Dead Bug – Fersen-Tippen',
    description: 'Beine abwechselnd im 90°-Winkel absenken und antippen, Rücken bleibt ruhig.',
    instructions: ['Rückenlage, Knie über der Hüfte im 90°-Winkel.', 'Ausatmen: eine Ferse Richtung Boden tippen.', 'Einatmen: zurück.', 'Seitenwechsel.'],
    breathing: 'Ausatmen beim Absenken',
    targetMuscles: ['Tiefe Bauchmuskeln'],
    difficulty: 3,
    duration: 150,
    repetitions: 8,
    phase: p(3),
    regressions: ['heel-slide'],
    progressions: ['dead-bug-alternating'],
    contraindications: [pain(), pressure(), doming(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'bird-dog',
    name: 'Bird Dog',
    description: 'Im Vierfüßlerstand Arm und gegenüberliegendes Bein strecken.',
    instructions: ['Vierfüßlerstand.', 'Ausatmen: ein Bein nach hinten schieben.', 'Später gegenüberliegenden Arm dazunehmen.', 'Becken bleibt ruhig.'],
    breathing: 'Ausatmen beim Strecken',
    targetMuscles: ['Rumpf', 'Gesäß', 'Rücken'],
    difficulty: 3,
    duration: 150,
    repetitions: 8,
    phase: p(3),
    regressions: ['quadruped-weight-shift'],
    progressions: [],
    contraindications: [pain(), pressure(), doming(), cesarean()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'side-lying-leg-lift',
    name: 'Seitliches Beinheben',
    description: 'In Seitenlage das obere Bein kontrolliert anheben.',
    instructions: ['Seitenlage, unteres Bein angewinkelt.', 'Ausatmen: oberes Bein gestreckt anheben.', 'Einatmen: kontrolliert absenken.'],
    breathing: 'Ausatmen beim Anheben',
    targetMuscles: ['Seitliche Hüfte', 'Gesäß'],
    difficulty: 3,
    duration: 150,
    repetitions: 10,
    phase: p(3),
    regressions: ['clamshell'],
    progressions: [],
    contraindications: [pain(), pressure(), perineal()],
  }),
  ex({
    id: 'supported-squat',
    name: 'Kniebeuge mit Halt',
    description: 'Kniebeuge mit Festhalten an Stuhl oder Türrahmen.',
    instructions: ['Hüftbreit stehen, Halt greifen.', 'Einatmen: Gesäß nach hinten unten schieben.', 'Ausatmen: aufrichten.', 'Nicht pressen.'],
    breathing: 'Ausatmen beim Aufrichten',
    targetMuscles: ['Oberschenkel', 'Gesäß', 'Beckenboden'],
    difficulty: 3,
    duration: 150,
    repetitions: 10,
    phase: p(3),
    regressions: ['sit-to-stand'],
    progressions: [],
    contraindications: [pain(), pressure(), cesarean()],
    equipment: ['Stuhl oder Türrahmen'],
  }),

  // ---------- Phase 4: Belastbarkeit ----------
  ex({
    id: 'dead-bug-alternating',
    name: 'Dead Bug – Arm & Bein',
    description: 'Gegenüberliegende Arm-Bein-Bewegung in Rückenlage.',
    instructions: ['Rückenlage, Arme zur Decke, Knie im 90°-Winkel.', 'Ausatmen: gegenüberliegenden Arm und Bein absenken.', 'Einatmen: zurück.', 'Rücken bleibt ruhig.'],
    breathing: 'Ausatmen beim Absenken',
    targetMuscles: ['Tiefe Bauchmuskeln', 'Rumpf'],
    difficulty: 4,
    duration: 180,
    repetitions: 8,
    phase: p(4),
    regressions: ['dead-bug-heel-tap'],
    progressions: [],
    contraindications: [pain(), pressure(), doming(), cesarean(), clearance()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'single-leg-bridge',
    name: 'Einbeinige Brücke',
    description: 'Glute Bridge mit einem ausgestreckten Bein.',
    instructions: ['Glute Bridge einnehmen.', 'Ein Bein strecken.', 'Becken waagerecht halten, Ausatmen beim Anheben.'],
    breathing: 'Ausatmen beim Anheben',
    targetMuscles: ['Gesäß', 'Beinrückseite', 'Rumpf'],
    difficulty: 4,
    duration: 180,
    repetitions: 8,
    phase: p(4),
    regressions: ['marching-bridge'],
    progressions: [],
    contraindications: [pain(), pressure(), doming(), cesarean(), clearance()],
    stopCriteria: stop('doming'),
    domingWarning: true,
  }),
  ex({
    id: 'suitcase-carry',
    name: 'Koffer-Tragen',
    description: 'Leichtes Gewicht aufrecht tragen, trainiert Rumpfstabilität im Alltag.',
    instructions: ['Gewicht mit einer Hand tragen.', 'Aufrecht gehen, Schultern locker.', 'Gleichmäßig atmen, nicht Luft anhalten.', 'Seitenwechsel.'],
    breathing: 'Gleichmäßig atmen',
    targetMuscles: ['Rumpf', 'Schultern', 'Hüfte'],
    difficulty: 4,
    duration: 120,
    phase: p(4),
    regressions: ['supported-squat'],
    progressions: [],
    contraindications: [pain(), pressure(), doming(), cesarean(), clearance()],
    stopCriteria: stop('doming'),
    domingWarning: true,
    equipment: ['leichtes Gewicht (z. B. Wasserflasche)'],
  }),
]

export const exerciseById = (id: string): Exercise | undefined => exercises.find((e) => e.id === id)
